2021-12-17 15:50:40,882 ERROR: Exception on /add_interview [GET] [in /home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/flask_app/app/routes.py", line 207, in add_interview
    return render_template('add_interview.html', title='Add Interview', form=form)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/anastasiia/projects/flask_app/app/templates/add_interview.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/anastasiia/projects/flask_app/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/anastasiia/projects/flask_app/app/templates/add_interview.html", line 43, in block 'content'
    <!--            {{ form.users.label }}<br>-->
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.AddInterviewForm object' has no attribute 'users'
2021-12-17 15:51:37,848 INFO: Microblog startup [in /home/anastasiia/projects/flask_app/app/__init__.py:43]
2021-12-17 15:51:42,205 ERROR: Exception on /add_interview [GET] [in /home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/flask_app/app/routes.py", line 207, in add_interview
    return render_template('add_interview.html', title='Add Interview', form=form)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/anastasiia/projects/flask_app/app/templates/add_interview.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/anastasiia/projects/flask_app/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/anastasiia/projects/flask_app/app/templates/add_interview.html", line 43, in block 'content'
    <!--            {{ form.users.label }}<br>-->
  File "/home/anastasiia/projects/flask_app/venv/lib/python3.8/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.forms.AddInterviewForm object' has no attribute 'users'
2021-12-17 15:51:55,964 INFO: Microblog startup [in /home/anastasiia/projects/flask_app/app/__init__.py:43]
