2021-12-22 20:29:50,178 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:30:17,186 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:30:39,076 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:31:03,674 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:31:06,969 ERROR: Exception on /user/romanrom [GET] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 99, in user
    for grade in grades:
TypeError: 'Grade' object is not iterable
2021-12-22 20:31:39,778 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:32:16,131 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:32:33,028 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:32:53,749 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:33:22,166 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:33:42,076 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:49:19,423 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:49:22,440 ERROR: Exception on /user/romanrom [GET] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 97, in user
    grades = Grade.query.filter_by(interview=interview.id).all()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1793, in filter_by
    clauses = [
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1794, in <listcomp>
    _entity_namespace_key(from_entity, key) == value
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/sql/operators.py", line 360, in __eq__
    return self.operate(eq, other)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 317, in operate
    return op(self.comparator, *other, **kwargs)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 1317, in __eq__
    self.property._optimized_compare(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/relationships.py", line 1705, in _optimized_compare
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Mapped instance expected for relationship comparison to object.   Classes, queries and other SQL elements are not accepted in this context; for comparison with a subquery, use Grade.interview.has(**criteria).
2021-12-22 20:49:44,139 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:50:01,449 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:51:54,139 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:52:13,813 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:52:28,599 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:52:59,615 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:53:16,941 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:53:30,307 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:53:40,947 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:58:12,253 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:59:06,277 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 20:59:49,579 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:00:16,792 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:02:03,885 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:02:42,431 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:03:18,235 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:03:24,642 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 241, in edit_grade
    g.interviewer = request.form['interviewers']
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 459, in __set__
    self.impl.set(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1268, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1294, in fire_replace_event
    value = fn(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 119, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2021-12-22 21:07:09,471 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:08:02,210 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:08:08,061 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 241, in edit_grade
    g.interviewer = request.form.interviewers
AttributeError: 'ImmutableMultiDict' object has no attribute 'interviewers'
2021-12-22 21:09:14,699 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
