2021-12-27 12:10:14,098 ERROR: Exception on /login [GET] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 42, in login_route
    return render_template('login.html', title='Sign In', form=form)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/templates/base.html", line 41, in top-level template code
    {% block content %}{% endblock %}
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/templates/login.html", line 27, in block 'content'
    <p>New User? <a class="btn btn-outline-dark me-2" href="{{ url_for('register') }}" role="button">Click to Register!</a></p>
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'register'. Did you mean 'register_route' instead?
2021-12-27 12:10:55,899 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:53]
2021-12-27 12:11:11,344 ERROR: Exception on /logout [GET] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 48, in logout_route
    return redirect(url_for('login'))
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'login_route' instead?
2021-12-27 12:13:33,779 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:53]
