2021-12-22 21:09:19,747 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 241, in edit_grade
    g.interviewer = request.form.get(interviwers)
NameError: name 'interviwers' is not defined
2021-12-22 21:10:32,494 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:10:39,500 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 241, in edit_grade
    g.interviewer = int(request.form['interviewers'])
ValueError: invalid literal for int() with base 10: 'Anastasiia Blyzniuk'
2021-12-22 21:14:24,217 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:14:29,234 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 241, in edit_grade
    g.interviewer = request.form['interviewers']
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 459, in __set__
    self.impl.set(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1268, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1294, in fire_replace_event
    value = fn(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 119, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2021-12-22 21:15:14,303 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:15:17,957 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 241, in edit_grade
    g.interviewer = request.form['interviewers']
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 459, in __set__
    self.impl.set(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1268, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1294, in fire_replace_event
    value = fn(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 119, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2021-12-22 21:16:04,865 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:17:02,292 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:17:23,834 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:17:45,171 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:18:05,293 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:18:27,542 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:18:39,291 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 241, in edit_grade
    g.interviewer = request.form['interviewers']
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 459, in __set__
    self.impl.set(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1268, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 1294, in fire_replace_event
    value = fn(
  File "/home/anastasiia/.local/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 119, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'str' object has no attribute '_sa_instance_state'
2021-12-22 21:23:01,613 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
2021-12-22 21:23:08,938 ERROR: Exception on /edit_grade/50 [POST] [in /home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/anastasiia/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/anastasiia/projects/softserve_internship/flask_app/app/routes.py", line 238, in edit_grade
    g.standard.docs.insert({
AttributeError: 'Grade' object has no attribute 'standard'
2021-12-22 21:25:58,233 INFO: Microblog startup [in /home/anastasiia/projects/softserve_internship/flask_app/app/__init__.py:47]
